package com.hlr.huawei.enumerator;

public enum GsType {
    CLIP, CLIR, COLP, COLR, MCI, CNAP, ECT, MAH, HOLD, CCBS_A, CCBS_B, AOCC, AOCI, MPTY, HOTBILL, CAPL,
    PLMNSS1, PLMNSS2, PLMNSS3, PLMNSS4, PLMNSS5, PLMNSS6, PLMNSS7, PLMNSS8, PLMNSS9,
    PLMNSSA, PLMNSSB, PLMNSSC, PLMNSSD, PLMNSSE, PLMNSSF, ALLPLMNSS, CD, ELCS, CPP,
    ICSIND, ANCHOR, SELECTIVE, TCSI, PRE_FALSE, PRE_TRUE
}
