#spring:
#    jpa:
#        generate-ddl: false
#        hibernate:
#            ddl-auto: false
hlr:
    file:
        chunk: 100
        name: hlrHuawei.dat
        path: /apps/data/java/parseHlrHuawei/conf
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE
spring:
    datasource:
        driver:
            class: oracle.jdbc.driver.OracleDriver
        hikari:
            maximum-pool-size: 20
            data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 250
                    prepStmtCacheSqlLimit: 2048
                    useServerPrepStmts: true
                    useLocalSessionState: true
                    rewriteBatchedStatements: true
                    cacheResultSetMetadata: true
                    cacheServerConfiguration: true
                    elideSetAutoCommits: true
                    maintainTimeStats: false
        initialize: false
        password: RAIDPI_DAT
        url: jdbc:oracle:thin:@brux0604:1521/T00RE4
        username: RAIDPI_DAT
    jpa:
        database-platform: org.hibernate.dialect.Oracle12cDialect
        properties:
            dialect: org.hibernate.dialect.Oracle12cDialect
            hibernate:
                format_sql: true
                show_sql: true
        show-sql: true
